In [10]:
import torch

x = torch.ones(5) # input tensor
y = torch.zeros(3) # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [17]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x00000153999A6050>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x00000153C346B9D0>


In [18]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.2020, 0.2714, 0.1489],
        [0.2020, 0.2714, 0.1489],
        [0.2020, 0.2714, 0.1489],
        [0.2020, 0.2714, 0.1489],
        [0.2020, 0.2714, 0.1489]])
tensor([0.2020, 0.2714, 0.1489])


In [19]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w) + b
print(z.requires_grad)

True
False


In [23]:
z = torch.matmul(x, w ) + b
print(z.requires_grad)

z_det = z.detach()
print(z_det.requires_grad)

True
False


In [ ]:
inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}\n")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"Second call\n{inp.grad}\n")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"Call after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])


In [31]:
inp.grad.shape

torch.Size([4, 5])